import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml",
    #"~/.config/alacritty/catppuccin-mocha.toml",
    #"~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "general"]

[window]
opacity = 0.80

[font]
normal= { family= "FiraCode Nerd Font Mono", style= "Medium" }
bold= { family= "FiraCode Nerd Font Mono", style= "Bold" }
italic= { family= "FiraCode Nerd Font Mono", style= "Retina" }
bold_italic= { family= "FiraCode Nerd Font Mono", style= "SemiBold" }
size = 9.5
